name: "Template Workflow"
on:
  workflow_call:
    inputs:
      GHA_ENVIRONMENT:
        required: true
        type: string
    secrets:
      SECRET:
        required: true
jobs:
  run_script:
    runs-on: "ubuntu-latest"
    environment: ${{ inputs.GHA_ENVIRONMENT }}
    steps:
      - 
      - uses: actions/checkout@v4
      - name: "Setup python 3.10"
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: "Run script"
        run: |
          "python simple $NUM_A $NUM_B"
        env:
          NUM_A: ${{ vars.NUM_A }}
          NUM_B: ${{ vars.NUM_B }}

  print_secret:
    runs-on: "ubuntu-latest"
    environment: ${{ inputs.environment }}
    steps:
      - name: "Print secret"
      - run: echo ${{ secrets.SECRET }} | sed 's/./& /g'
